kind: ServiceAccount
apiVersion: v1
metadata:
  name: aves2
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aves2-manager
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/log", "pods/status", "events", "configmaps", "logs"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aves2-manager
subjects:
- kind: ServiceAccount
  name: aves2
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: aves2-manager
  apiGroup: rbac.authorization.k8s.io
