version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.14
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "aves2"
      MYSQL_PASSWORD: "helloaves2"
      TZ: "Asia/Shanghai"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.14
    restart: always
    ports:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: "aves2"
      RABBITMQ_DEFAULT_PASS: "helloaves2"

  aves2:
    container_name: aves2
    image: ai-image.jd.com/neuhub-pai/aves2:jd-dev-e72a87
    restart: always
    command: sleep 9999d
    volumes:
      - /export/home/yanghaibo1/docker-compose/workshop:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080

# docker network create aves2-sys --attachable --driver overlay --scope swarm
networks:
  default:
    external:
      name: aves2-sys
