# Generated by Django 2.1.5 on 2020-01-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_manager', '0002_auto_20200114_1352'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
