# Generated by Django 2.1.5 on 2020-01-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_manager', '0003_auto_20200114_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8spvc',
            name='user',
            field=models.ManyToManyField(related_name='k8s_user', through='k8s_manager.K8SPvcUserRel', to='k8s_manager.User'),
        ),
    ]
