# Generated by Django 2.2 on 2020-06-18 02:58

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import job_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvesJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('describe', models.CharField(blank=True, default='', max_length=1024)),
                ('username', models.CharField(default='', max_length=128)),
                ('namespace', models.CharField(default='default', max_length=64)),
                ('job_id', models.CharField(default='none', max_length=128)),
                ('engine', models.CharField(max_length=64)),
                ('is_distribute', models.BooleanField(blank=True, default=False)),
                ('distribute_type', models.CharField(blank=True, choices=[('TF_PS', 'TF_PS'), ('HOROVOD', 'HOROVOD')], max_length=64, null=True)),
                ('debug', models.BooleanField(blank=True, default=True)),
                ('image', models.CharField(max_length=512)),
                ('package_uri', models.CharField(blank=True, default='', max_length=512)),
                ('resource_spec', django_mysql.models.JSONField(default=job_manager.models.json_field_default)),
                ('storage_mode', models.CharField(default='OSSFile', max_length=32)),
                ('storage_config', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default)),
                ('envs', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default)),
                ('code_spec', django_mysql.models.JSONField(default=job_manager.models.json_field_default)),
                ('input_spec', django_mysql.models.JSONField(default=job_manager.models.json_field_default)),
                ('output_spec', django_mysql.models.JSONField(default=job_manager.models.json_field_default)),
                ('log_dir', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default)),
                ('mount_node_storage', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(blank=True, choices=[('NEW', '新建'), ('STARTING', '启动中'), ('PENDING', '等待中'), ('RUNNING', '运行中'), ('FINISHED', '已结束'), ('FAILURE', '已失败'), ('CANCELED', '已取消')], default='NEW', max_length=16)),
                ('need_report', models.BooleanField(blank=True, default=False)),
                ('token', models.CharField(blank=True, default='', max_length=16)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'avesjob',
            },
        ),
        migrations.CreateModel(
            name='AvesWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=128)),
                ('namespace', models.CharField(max_length=32)),
                ('engine', models.CharField(max_length=64)),
                ('worker_name', models.CharField(default='', max_length=256)),
                ('is_main_node', models.BooleanField(blank=True, default=True)),
                ('avesrole', models.CharField(default='worker', max_length=16)),
                ('role_index', models.IntegerField(default=0)),
                ('cpu_request', models.IntegerField(default=4, verbose_name='REQCPU')),
                ('cpu_limit', models.IntegerField(blank=True, null=True, verbose_name='LIMCPU')),
                ('mem_request', models.IntegerField(default=8, verbose_name='REQMEM(Gi)')),
                ('mem_limit', models.IntegerField(blank=True, default=8, null=True, verbose_name='LIMMEM(Gi)')),
                ('gpu_request', models.IntegerField(blank=True, null=True, verbose_name='REQGPU')),
                ('entrypoint', models.CharField(blank=True, default='', max_length=512)),
                ('args', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default_list)),
                ('ports', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default_list)),
                ('k8s_status', models.CharField(blank=True, choices=[('NEW', '新建'), ('STARTING', '启动中'), ('PENDING', '等待中'), ('RUNNING', '运行中'), ('FINISHED', '已结束'), ('FAILURE', '已失败'), ('CANCELED', '已取消')], default='NEW', max_length=32)),
                ('worker_ip', models.CharField(blank=True, max_length=32, null=True)),
                ('worker_json', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default, null=True)),
                ('service_json', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default, null=True)),
                ('ingress_json', django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('avesjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aves_worker', to='job_manager.AvesJob')),
            ],
            options={
                'db_table': 'avesworker',
            },
        ),
    ]
