# Generated by Django 2.2 on 2020-06-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avesjob',
            name='msg',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
