# Generated by Django 2.1.5 on 2020-02-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8sworker',
            name='k8s_status',
            field=models.CharField(blank=True, choices=[('NEW', '新建'), ('STARTING', '启动中'), ('PENDING', '等待中'), ('RUNNING', '运行中'), ('FINISHED', '已结束'), ('FAILURE', '已失败'), ('CANCELED', '已取消')], default='NEW', max_length=32),
        ),
    ]
