# Generated by Django 2.1.5 on 2020-01-16 07:59

from django.db import migrations, models
import django_mysql.models
import job_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avesjob',
            name='code_spec',
            field=django_mysql.models.JSONField(default=job_manager.models.json_field_default),
        ),
        migrations.AlterField(
            model_name='k8sworker',
            name='k8s_status',
            field=models.CharField(blank=True, choices=[('NEW', '新建'), ('STARTING', '启动中'), ('PENDING', '等待中'), ('RUNNING', '运行中'), ('FINISHED', '已结束'), ('FAILURE', '已失败'), ('CANCELED', '已取消')], default='NEW', max_length=32),
        ),
    ]
