# Generated by Django 2.1.5 on 2020-02-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0002_auto_20200116_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avesjob',
            name='job_id',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
