# Generated by Django 2.1.5 on 2020-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0003_auto_20200213_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='avesjob',
            name='debug',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
