# Generated by Django 2.2 on 2020-02-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0004_avesjob_debug'),
    ]

    operations = [
        migrations.AddField(
            model_name='avesjob',
            name='describe',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='avesjob',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
