# Generated by Django 2.2 on 2020-02-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0005_auto_20200222_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='avesjob',
            name='need_report',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
