# Generated by Django 2.2 on 2020-03-01 13:27

from django.db import migrations
import django_mysql.models
import job_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0006_avesjob_need_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avesjob',
            name='log_dir',
            field=django_mysql.models.JSONField(blank=True, default=job_manager.models.json_field_default),
        ),
    ]
