# Generated by Django 2.2 on 2020-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0007_auto_20200301_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avesjob',
            name='debug',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
